keyid-format 0xlong
with-fingerprint
armor
no-emit-version
keyserver hkps://keyserver.ubuntu.com:443
sig-keyserver-url hkps://keyserver.ubuntu.com:443
keyserver-options no-honor-keyserver-url
use-agent
