-- Unmap normal mode C-a (my tmux prefix)
vim.keymap.set('n', '<C-a>', '<Nop>', {noremap = true})

-- Split navigations
vim.keymap.set('t', '<A-h>', '<C-\\><C-N><C-w>h', {noremap = true})
vim.keymap.set('t', '<A-j>', '<C-\\><C-N><C-w>j', {noremap = true})
vim.keymap.set('t', '<A-k>', '<C-\\><C-N><C-w>k', {noremap = true})
vim.keymap.set('t', '<A-l>', '<C-\\><C-N><C-w>l', {noremap = true})
vim.keymap.set('i', '<A-h>', '<C-\\><C-N><C-w>h', {noremap = true})
vim.keymap.set('i', '<A-j>', '<C-\\><C-N><C-w>j', {noremap = true})
vim.keymap.set('i', '<A-k>', '<C-\\><C-N><C-w>k', {noremap = true})
vim.keymap.set('i', '<A-l>', '<C-\\><C-N><C-w>l', {noremap = true})
vim.keymap.set('n', '<A-h>', '<C-w>h', {noremap = true})
vim.keymap.set('n', '<A-j>', '<C-w>j', {noremap = true})
vim.keymap.set('n', '<A-k>', '<C-w>k', {noremap = true})
vim.keymap.set('n', '<A-l>', '<C-w>l', {noremap = true})
